### ISSUE TITLE
Intel Python is 4 seconds slower than Anaconda Python

### ISSUE THREAD

**Issue by FuriouslyCurious** [IntelPython/optimizations_bench#3]
I am testing Intel Xeon Phi KNL x200 processor with 64-cores.

I have set up Intel Python and make sure it works.  Intel Python is super slow compared to Anaconda Python.   What is the reason for that?

Outputs:

```
# Intel Python without binding to HBM memory:
time miniconda3/envs/intel3/bin/python numpy/umath/umath_mem_bench.py -v --size 10 --goal-time 0.01 --repeats 1
?, ?,  copyto, float64,       1,      10,  12454.00,  13116.00
23.82user 0.21system 0:24.12elapsed 99%CPU (0avgtext+0avgdata 22964maxresident)k
0inputs+0outputs (0major+20673minor)pagefaults 0swaps


# Intel Python with binding to HBM memory
numactl -m 1 time miniconda3/envs/intel3/bin/python numpy/umath/umath_mem_bench.py -v --size 10 --goal-time 0.01 --repeats 1
?, ?,  copyto, float64,       1,      10,  12809.80,  21868.00
**27.02user** 0.19system 0:27.30elapsed 99%CPU (0avgtext+0avgdata 22956maxresident)k
0inputs+0outputs (0major+6080minor)pagefaults 0swaps


# Anaconda Python
time python numpy/umath/umath_mem_bench.py -v --size 10 --goal-time 0.01 --repeats 1
?, ?,  copyto, float64,       1,      10,  13182.00,  22733.80
**20.22user** 0.23system 0:20.54elapsed 99%CPU (0avgtext+0avgdata 25864maxresident)k
0inputs+0outputs (0major+18901minor)pagefaults 0swaps
```

**Comment by anton-malakhov** [comment]
How have you made this conclusion? Is it based on this test only or through some other experience?

With regard to the output cited above, the numbers from the benchmark itself (12454 < 13181) object to your statement.
I could see that you might want to choose these command line arguments: because you wanted to compare total overhead in both distributions which is not specific to this bench though.. but let me first clarify at least for others why using these settings is generally a bad idea:

1. Using `time` utility for a benchmark:
1.1. Benchmarks might be designed in a way which make different runs incomparable from the external point of view.  Standard Python's `timeit`, this particular bench, and other frameworks like Airspeed Velocity use calibration runs to adjust number of iterations to fit reasonable amount of time for measurement. It is quite likely that faster function can take longer time to measure just because it is run 10x more times than slower function. 
1.2. Using CPU time is wrong for multi-threaded applications. Not for this case because with size=10 it runs single threaded, but for sake of complete answer, let me put it here. CPU time sums time of all the threads which might be just busy-waiting for a work to arrive in order to start it faster. This is usual trick for both Intel OpenMP runtime and Intel TBB to improve wall-time.
2. Benchmark settings which measure rather overheads than real compute speeds:
2.1. `--goal-time 0.01` is 0.01 milliseconds, which is beyond the timer accuracy on some platforms (unless rdtsc is used), increasing error in the bench's results. It happens to force just single internal iteration on my machine but without seeing your full log I'm not that sure that the same happens for you as well.
2.2. `--repeats 1` often does not return stable results. In our experience, in order to start getting stable results, one needs at least 30 (default) measurements with default `goal-time`. Otherwise, different runs might produce results which differ by a big margin, up to an order of magnitude. If you do want to measure overhead for the first run.. it is still slightly off the target since there are mandatory warm-up, calibration runs, and internal iterations anyway.
2.3. `--size 10` is useful only to measure overheads of broadcasting function calls but certainly not with such values of the options above. Otherwise, deliberately measuring performance of arrays with size 10 makes no sense to me since if one chooses Python for computing such small arrays, it means performance is irrelevant. Unless a JIT compiler used, Python is just wrong language for such a small computation.

If you want to measure overheads of individual function calls, I would recommend running `umath_mem_bench.py -v --size 10 --repeat 3` instead. With such a small size, `repeat` argument can be small enough because no threading and cache effects are involved. However, small `--goal-time` results in ridiculous values unless compensated with large repeat numbers (>1000) but even in this case, it runs much slower and still giving unstable results. 

But if my guess with your goals is correct, it means you are complaining on the speed of the python interpreter itself or related infrastructure of Numpy, but not on any optimizations we did to speed-up the computations themselves. My best guess is that you are comparing different versions of the Python interpreter. In our setup, when both distros use Python 3.5.3, we see no meaningful difference.
